"use client";
import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Edit3 } from "lucide-react";

interface DemoAlertProps {
  isPersonalized: boolean;
  brand: string;
  onOpenCustomizer: () => void;
}

export default function DemoAlert({ isPersonalized, brand, onOpenCustomizer }: DemoAlertProps) {
  const [isVisible, setIsVisible] = useState(true);

  useEffect(() => {
    if (!isPersonalized) {
      const timer = setTimeout(() => setIsVisible(false), 8000);
      return () => clearTimeout(timer);
    }
  }, [isPersonalized]);

  return (
    <AnimatePresence>
      {isVisible && (
        <motion.div
          initial={{ y: 100, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          exit={{ y: 100, opacity: 0 }}
          className="fixed bottom-8 left-1/2 -translate-x-1/2 z-[90] w-full max-w-md px-6"
        >
          <div className="bg-white/90 backdrop-blur-xl border border-indigo-100 p-5 rounded-3xl shadow-2xl flex items-center justify-between gap-6">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 bg-indigo-600 text-white rounded-full flex items-center justify-center shrink-0">
                <Sparkles size={18} />
              </div>
              <div>
                <p className="text-sm font-bold text-slate-900">
                  {isPersonalized ? `Preview for ${brand}` : "Personalize this demo"}
                </p>
                <p className="text-[11px] text-slate-500 font-medium">
                  {isPersonalized ? "Generated by BizSite Studio" : "See your brand here in seconds."}
                </p>
              </div>
            </div>

            <button
              onClick={onOpenCustomizer}
              className="px-5 py-2.5 bg-slate-900 text-white text-xs font-bold rounded-full hover:bg-indigo-600 transition-all flex items-center gap-2"
            >
              {isPersonalized ? "Edit Info" : "Customize"}
              <Edit3 size={14} />
            </button>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}